sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby
  - rbx-2
  - ruby-head
  - jruby-head
  - rbx-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
before_install: gem install bundler
